### ISSUE TITLE
freetype

### ISSUE THREAD

**Issue by dprestegard** [master-of-zen/Av1an#72] opened 2020-05-21 18:53 UTC
Looks like freetype is required, but this is not mentioned in the readme :)

**Comment by lastrosade** [comment] 2020-05-21 19:55
It does not.

**Comment by dprestegard** [comment] 2020-05-21 19:58
Hmm. When I do `python setup.py install` I get:

```
Installed c:\users\presd035\appdata\local\temp\1\easy_install-pvtcbrle\matplotlib-3.2.1\.eggs\numpy-1.19.0rc1-py3.8-win-amd64.egg
UPDATING build\lib.win-amd64-3.8\matplotlib\_version.py
set build\lib.win-amd64-3.8\matplotlib\_version.py to '3.2.1'
checkdep_freetype2.c
src/checkdep_freetype2.c(5): fatal error C1189: #error:  "FreeType version 2.3 or higher is required. You may set the MPLLOCALFREETYPE environment variable to 1 to let Matplotlib download it."
error: [WinError 5] Access is denied: 'C:\\Users\\presd035\\AppData\\Local\\Temp\\1\\easy_install-pvtcbrle\\matplotlib-3.2.1\\.eggs\\numpy-1.19.0rc1-py3.8-win-amd64.egg\\numpy\\core\\_multiarray_tests.cp38-win_amd64.pyd'
```

**Comment by farid-fari** [comment] 2020-05-21 21:36
It doesn't require freetype, it requires matplotlib which in turn requires freetype. Just like it doesn't require a CPU, but Python requires a CPU to run, we just don't put it in the README because we're not pedants.

**Comment by dprestegard** [comment] 2020-05-21 21:40
Well come on now. Isn't the whole point of the package manager + setup script to resolve all those dependencies? The readme should contain all info needed to setup the tool.

**Comment by farid-fari** [comment] 2020-05-21 21:45
Pip cannot install freetype or cython, these are things you need to do yourself prior to installing this package, just like the package can't install Windows or linux on your computer for you. We can add freetype to the README if it really pleases you but it won't change the fact that you have to go to your package manager/internet and get it and install it yourself.

**Comment by dprestegard** [comment] 2020-05-21 21:47
Again yes I think the readme should clearly show any dependencies it’s unable to resolve for you.

**Comment by farid-fari** [comment] 2020-05-21 22:13
But freetype isn't a direct dependency, it's a dependency of a dependency. If you start listing those, there are hundred of libraries Python relies upon, do we list all these too?

**Comment by luigi311** [comment] 2020-05-21 22:15
when you do a pip install -r requirements.txt it will install all the dependencies and their dependencies and their dependencies and so on and so on. During that process freetype will be installed for you as matplotlib requires it.

**Comment by dprestegard** [comment] 2020-05-21 22:16
Yeah, I think that just adding `pip install -r requirements.txt` to the readme would solve the problem completely :)

**Comment by luigi311** [comment] 2020-05-21 22:17
I'm actually surprised that it's not, we will go ahead and add that to the instructions.

**Comment by dprestegard** [comment] 2020-05-21 22:19
Excellent! That's good news. I imagine this would have been obvious to people more familiar with the different ways people handle dependencies in python apps, but not all of us are so familiar. This will make things much more noob friendly :)

**Comment by luigi311** [comment] 2020-05-21 22:21
Agreed

**Comment by farid-fari** [comment] 2020-05-21 22:23
I maintain however that freetype is an independent library which cannot be installed by pip. You install it manually, or your package manager pulls it in as a dependency if you install matplotlib with your package manager, but running `pip install -r requirements.txt` will not install it.

**Comment by luigi311** [comment] 2020-05-21 22:26
Pip can install freetype. Here is the pypy package that will install a binary for freetype https://pypi.org/project/freetype-py/

**Comment by dprestegard** [comment] 2020-05-21 22:29
^ I did actually perform that step as I chased this issue.

**Comment by luigi311** [comment] 2020-05-21 22:30
And did it solve your issues?

**Comment by dprestegard** [comment] 2020-05-21 22:32
Not sure if it was that step or `pip install -r requirements.txt` but after I did both of those things the script does run. I'm having issues with some fun errors (which we're tracking in https://github.com/master-of-zen/Av1an/issues/73) but I don't appear to be missing any libraries.

**Comment by luigi311** [comment] 2020-05-21 22:49
Looks like the setup.py has the install_requires flag on it so it should be installing decencies that pip is able to install. I am getting an error about C++ 14.0 is required in windows though.

**Comment by luigi311** [comment] 2020-05-21 23:02
Looks like it did attempt to install the requirements but failed due to permission issues. I will be adding the --user flag to the instructions and including the link to the link to the c++ build tools. Freetype is failing to install though via the setup.py process.

**Comment by farid-fari** [comment] 2020-05-21 23:03
@luigi311 we should recommend people use a virtual environement rather than `--user`, which is much messier and less recommended

**Comment by luigi311** [comment] 2020-05-21 23:06
the problem with virtual environments is that users are not going to know how to create and activate them every single time they want to run av1an.

**Comment by luigi311** [comment] 2020-05-21 23:12
Also would virtual env not be included in the PATH by default so users would have to add the location of the virtual env to their PATH manually?

**Comment by farid-fari** [comment] 2020-05-21 23:15
You don't really need to add it to your PATH, you just activate it with the `bin/activate` script and it will modify the environement suitably (including the PATH).

Honestly I don't think we should be worrying about all this, it is up to users to setup their Python environment. There are thousands of Python packages out there and none detail how to setup a virtualenv, they just recommend users do it and provide a link...

**Comment by luigi311** [comment] 2020-05-21 23:17
That is also true. Back to freetype, python setup.py will not install it as it wants to use the system version of freetype unless you set a env variable, pip will install it but its not recommended to have both a setup.py with requirements and a requirements.txt file due to them getting out of sync.

**Comment by farid-fari** [comment] 2020-05-21 23:30
As far as I know, you need a system (or user) install of libfreetype to use matplotlib, which pip can't do in either case. It might be possible to install matplotlib without the library but it might not work, especially with the default `tk` backend. If it works for @dprestegard though that's good, but I definitely don't know why.

I don't think `freetype-py` cuts it, that's a different implementation of freetype, in python, that matplotlib shouldn't be using.

**Comment by luigi311** [comment] 2020-05-21 23:39
I can confirm that pip install the requirements does fix the issue.

**Comment by farid-fari** [comment] 2020-05-22 00:14
@luigi311 did you try plotting something with text in it? What backend are you using?

I'm pretty sure this wouldn't work on linux/OSX.

**Comment by luigi311** [comment] 2020-05-22 00:22
Yup just plotted with the plot_vmaf python script that uses matplotlib 
![plot](https://user-images.githubusercontent.com/4695527/82618313-f8802e00-9b8f-11ea-95bd-c2020ce8e522.png)

**Comment by farid-fari** [comment] 2020-05-22 00:27
Huh guess I was wrong then, sorry.

**Comment by luigi311** [comment] 2020-05-22 00:28
Its all good

**Closed** 2020-06-03 16:07 UTC
