### ISSUE TITLE
target-quality broken

### ISSUE THREAD

**Issue by damian101** [master-of-zen/Av1an#719] opened 2023-02-04 20:49 UTC
Just doesn't do anything. Still works on 0.4.0 branch.

**Comment by NZDivinity** [comment] 2023-02-04 23:42
Same issue. thought it was user error (first time using av1an) but issue is not present in 0.4.0

**Comment by BlueSwordM** [comment] 2023-02-19 03:54
Can't reproduce the issue :monkas:

**Comment by Werve** [comment] 2023-02-22 20:37
After many attempts believing that I got some input args wrong, I confirm that the latest version av1an.exe attached ignores the `--target-vmaf` argument and encodes the video in the normal way e.g. with `--crf`.

You can also check it by passing as argument `--min-q 1 `
the working version 0.4.0 shows the error 
`Error: Condition failed: `min_q > 1` (1 vs 1)` 
while the other one continues normally (ignores the argument)

I believe the versions installed with `cargo` are also affected by the problem

**Comment by piotrvass** [comment] 2023-03-14 11:36
I can confirm this also happens under new Arch package 0.4.1-1, --target-quality is never run due to changes in commit
 49b3f31 ("Refactor Chunk to be self-contained after generation (#714)", 2023-01-27)

From what I see it will run for some chunk methods, doesn't run 100% for vs pipes (LSMASH).

it's easy to replicate - just run any --target-quality conversion with lsmash. 
Proper log sequence is:
```
DEBUG [av1an_core::broker]  started chunk 00152: 239 frames
DEBUG [av1an_core::broker]  started chunk 00301: 234 frames
DEBUG [av1an_core::broker]  started chunk 00300: 233 frames
DEBUG [av1an_core::broker]  started chunk 00299: 233 frames
DEBUG [av1an_core::target_quality] chunk 00152: P-Rate=2, 239 frames
DEBUG [av1an_core::target_quality] chunk 00152: TQ-Probes: [(90.65, 35), (90.13, 37), (73.09, 60)]
DEBUG [av1an_core::target_quality] chunk 00152: Target Q=37, VMAF=90.00
DEBUG [av1an_core::target_quality] chunk 00300: P-Rate=2, 233 frames
DEBUG [av1an_core::target_quality] chunk 00300: TQ-Probes: [(97.18, 10), (90.06, 34), (89.33, 35)]
DEBUG [av1an_core::target_quality] chunk 00300: Target Q=34, VMAF=90.00
DEBUG [av1an_core::target_quality] chunk 00299: P-Rate=2, 233 frames
DEBUG [av1an_core::target_quality] chunk 00299: TQ-Probes: [(92.07, 35), (90.36, 39), (89.86, 40), (61.32, 60)]
DEBUG [av1an_core::target_quality] chunk 00299: Target Q=39, VMAF=90.00
DEBUG [av1an_core::target_quality] chunk 00301: P-Rate=2, 234 frames
DEBUG [av1an_core::target_quality] chunk 00301: TQ-Probes: [(92.33, 35), (89.95, 40), (89.60, 41), (76.39, 60)]
DEBUG [av1an_core::target_quality] chunk 00301: Target Q=39, VMAF=90.00
DEBUG [av1an_core::broker] finished chunk 00152: 239 frames, 0.55 fps, took 432.18s
DEBUG [av1an_core::broker]  started chunk 00298: 233 frames
```

with version 0.4.1 this doesn't happen - the target quality part is skipped going straight to conversion.

Created local patch for it, but don't like how it works (I never used rust so it's probably quite bad - but shows the error):
in av1an-core/src/settings.rs:
```

@@ -929,10 +929,13 @@ properly into a mkv file. Specify mkvmerge as the concatenation method by settin
         .zone_overrides
         .as_ref()
         .map_or(self.photon_noise, |ovr| ovr.photon_noise),
       self.chroma_noise,
     )?;
+    if let Some(ref tq) = self.target_quality {
+      tq.per_shot_target_quality_routine(&mut chunk)?;
+    }
     Ok(chunk)
   }
 
   fn create_video_queue_vs(&self, scenes: &[Scene], vs_script: &Path) -> Vec<Chunk> {
     let chunk_queue: Vec<Chunk> = scenes
@@ -1098,10 +1101,13 @@ properly into a mkv file. Specify mkvmerge as the concatenation method by settin
     };
     chunk.apply_photon_noise_args(
       overrides.map_or(self.photon_noise, |ovr| ovr.photon_noise),
       self.chroma_noise,
     )?;
+    if let Some(ref tq) = self.target_quality {
+      tq.per_shot_target_quality_routine(&mut chunk)?;
+    }
     Ok(chunk)
   }
 
   /// Returns unfinished chunks and number of total chunks
   fn load_or_gen_chunk_queue(&mut self, splits: &[Scene]) -> anyhow::Result<(Vec<Chunk>, usize)> {
```

With patch above all target quality calculations are done at the start before conversion starts:
```
DEBUG [av1an_core::target_quality] chunk 00000: P-Rate=2, 24 frames
DEBUG [av1an_core::target_quality] chunk 00000: TQ-Probes: [(97.43, 35), (97.43, 60)] Early Skip High Q
DEBUG [av1an_core::target_quality] chunk 00000: Target Q=60, VMAF=97.43
DEBUG [av1an_core::target_quality] chunk 00001: P-Rate=2, 125 frames
DEBUG [av1an_core::target_quality] chunk 00001: TQ-Probes: [(92.79, 35), (91.55, 40), (90.50, 42), (90.49, 43), (65.11, 60)]
DEBUG [av1an_core::target_quality] chunk 00001: Target Q=43, VMAF=90.00
DEBUG [av1an_core::target_quality] chunk 00002: P-Rate=2, 162 frames
DEBUG [av1an_core::target_quality] chunk 00002: TQ-Probes: [(93.33, 35), (92.64, 41), (90.63, 44), (89.43, 45), (66.71, 60)]
DEBUG [av1an_core::target_quality] chunk 00002: Target Q=44, VMAF=90.00
DEBUG [av1an_core::target_quality] chunk 00003: P-Rate=2, 162 frames
DEBUG [av1an_core::target_quality] chunk 00003: TQ-Probes: [(93.07, 35), (92.79, 40), (90.37, 43), (88.47, 44), (57.02, 60)]
DEBUG [av1an_core::target_quality] chunk 00003: Target Q=43, VMAF=90.00
DEBUG [av1an_core::target_quality] chunk 00004: P-Rate=2, 39 frames
DEBUG [av1an_core::target_quality] chunk 00004: TQ-Probes: [(91.80, 35), (90.99, 39), (90.53, 41), (89.35, 42), (72.07, 60)]
DEBUG [av1an_core::target_quality] chunk 00004: Target Q=41, VMAF=90.00
DEBUG [av1an_core::target_quality] chunk 00005: P-Rate=2, 110 frames
DEBUG [av1an_core::target_quality] chunk 00005: TQ-Probes: [(91.18, 35), (90.42, 37), (89.63, 38), (58.24, 60)]
DEBUG [av1an_core::target_quality] chunk 00005: Target Q=37, VMAF=90.00
DEBUG [av1an_core::target_quality] chunk 00006: P-Rate=2, 105 frames
DEBUG [av1an_core::target_quality] chunk 00006: TQ-Probes: [(91.40, 35), (90.28, 37), (60.07, 60)]
DEBUG [av1an_core::target_quality] chunk 00006: Target Q=37, VMAF=90.00
DEBUG [av1an_core::target_quality] chunk 00007: P-Rate=2, 231 frames
DEBUG [av1an_core::target_quality] chunk 00007: TQ-Probes: [(95.58, 10), (90.49, 28), (89.74, 29), (87.10, 35)]
DEBUG [av1an_core::target_quality] chunk 00007: Target Q=28, VMAF=90.00
DEBUG [av1an_core::target_quality] chunk 00008: P-Rate=2, 62 frames
DEBUG [av1an_core::target_quality] chunk 00008: TQ-Probes: [(90.10, 10), (90.07, 11), (84.18, 35)]
DEBUG [av1an_core::target_quality] chunk 00008: Target Q=11, VMAF=90.00
DEBUG [av1an_core::target_quality] chunk 00009: P-Rate=2, 211 frames
DEBUG [av1an_core::target_quality] chunk 00009: TQ-Probes: [(96.43, 10), (90.46, 32), (89.47, 33), (88.55, 35)]
DEBUG [av1an_core::target_quality] chunk 00009: Target Q=32, VMAF=90.00
DEBUG [av1an_core::target_quality] chunk 00010: P-Rate=2, 124 frames
DEBUG [av1an_core::target_quality] chunk 00010: TQ-Probes: [(92.31, 10), (92.18, 26), (91.93, 32), (89.98, 34), (88.54, 35)]
DEBUG [av1an_core::target_quality] chunk 00010: Target Q=33, VMAF=90.00
```

Which is not something I like/prefer so will probably revert to 0.4.0 for now before it's properly fixed.

**Comment by piotrvass** [comment] 2023-03-30 21:20
I've narrowed it down to this exact diff from mentioned commit - 49b3f31 ("Refactor Chunk to be self-contained after generation (#714)", 2023-01-27):
```
--------------------------- av1an-core/src/broker.rs ---------------------------
index 223fe75..60b0449 100644
@@ -18,7 +18,7 @@ use crate::settings::EncodeArgs;
 use crate::util::printable_base10_digits;
 use crate::{
   finish_multi_progress_bar, finish_progress_bar, get_done, Chunk, DoneChunk, Encoder, Instant,
-  TargetQuality, Verbosity,
+  Verbosity,
 };
 
 pub struct Broker<'a> {
@@ -26,7 +26,6 @@ pub struct Broker<'a> {
   pub chunk_queue: Vec<Chunk>,
   pub total_chunks: usize,
   pub project: &'a EncodeArgs,
-  pub target_quality: Option<TargetQuality<'a>>,
 }
 
 #[derive(Clone)]
@@ -206,31 +205,23 @@ impl<'a> Broker<'a> {
     let st_time = Instant::now();
 
     // space padding at the beginning to align with "finished chunk"
-    debug!(" started chunk {:05}: {} frames", chunk.index, chunk.frames);
-
-    if let Some(ref tq) = self.target_quality {
-      tq.per_shot_target_quality_routine(chunk)?;
-    }
+    debug!(
+      " started chunk {:05}: {} frames",
+      chunk.index,
+      chunk.frames()
+    );
```

this part exactly:
```
-    if let Some(ref tq) = self.target_quality {
-      tq.per_shot_target_quality_routine(chunk)?;
-    }
```

**Comment by luigi311** [comment] 2023-03-31 17:41
I can confirm that this does happen on some setups. On my docker container it will just skip the target-quality and do a normal encode. Even with a simple
av1an -i tt_sif.y4m -o 95.mkv -e x265 -v "-p 0 --crf 25" --target-quality 95 -c mkvmerge
av1an -i tt_sif.y4m -o 80.mkv -e x265 -v "-p 0 --crf 25" --target-quality 80 -c mkvmerge
the outputs end up exactly the same and the logs dont mention vmaf targeting  at all

DEBUG [av1an_core::settings] temporary directory: .e1fde64
INFO [av1an_core::settings] Input: 352x240 @ 29.970 fps, YUV420P, SDR
INFO [av1an_core::settings] scenecut: found 3 scene(s) [with extra_splits (299 frames): 3 scene(s)]
DEBUG [av1an_core::broker]  started chunk 00000: 67 frames
DEBUG [av1an_core::broker] finished chunk 00000: 67 frames, 553.08 fps, took 121.14ms
DEBUG [av1an_core::broker]  started chunk 00001: 30 frames
DEBUG [av1an_core::broker] finished chunk 00001: 30 frames, 373.51 fps, took 80.32ms
DEBUG [av1an_core::broker]  started chunk 00002: 15 frames
DEBUG [av1an_core::broker] finished chunk 00002: 15 frames, 204.21 fps, took 73.45ms
DEBUG [av1an_core::settings] encoding finished, concatenating with mkvmerge

**Comment by master-of-zen** [comment] 2023-04-06 03:17
Fixed in https://github.com/master-of-zen/Av1an/commit/45a927daeb49ffa180c70a1aecad49d59e433981

**Closed by master-of-zen** 2023-04-06 03:17 UTC
