### ISSUE TITLE
Scene detection error

### ISSUE THREAD

**Issue by phanluchoaofficial20** [master-of-zen/Av1an#395] opened 2021-11-01 16:29 UTC
Hello,

I have use your newest version and I got error Scene detection error when encoding, can anyone help me fix it ?

This is error:

D:\Av1an-1.12>av1an -i latmatnhacokhach.mkv -e x265 -s scenes.csv -w 4 -p 2 -o test1.mkv
Scene detection
[00:00:00] [-----------------------------------------------------------------------------------------------------------------------------]   0% 0/143836 (0.00 fps, eta 0s)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: End of file', av1an-core\src\settings.rs:482:8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Thanks!

**Comment by redzic** [comment] 2021-11-01 16:50
@phanluchoaofficial20 ffmpeg is not piping the file properly. Can you confirm that `ffmpeg -i latmatnhacokhach.mkv -f null -` works and does not display error messages?

**Comment by phanluchoaofficial20** [comment] 2021-11-01 16:54
> @phanluchoaofficial20 ffmpeg is not piping the file properly. Can you confirm that `ffmpeg -i latmatnhacokhach.mkv -f null -` works and does not display error messages?

Yes, it works normally

**Comment by redzic** [comment] 2021-11-01 16:56
Is it possible for you to upload a sample that doesn't work for you? It's completely understandable if it's not possible. Someone else had a different problem with the scene detection which turned out to be that ffmpeg behaved very strangely when piping that particular file, and it was fixed with PR #385 after I had a sample to see what the issue was.

**Comment by redzic** [comment] 2021-11-01 16:59
Can you also try this and post the output?

```
ffmpeg -i latmatnhacokhach.mkv -pix_fmt yuv420p10le -f null - | ffmpeg -i - -f null -
```

**Comment by phanluchoaofficial20** [comment] 2021-11-01 17:02
> Can you also try this and post the output?
> 
> ```
> ffmpeg -i latmatnhacokhach.mkv -pix_fmt yuv420p10le -strict -1 -f yuv4mpegpipe - | ffmpeg -i - -f null -
> ```

![Untitled](https://user-images.githubusercontent.com/86090065/139710609-c6fc9448-865d-43bd-b425-8a61e96597d3.png)

Here!

**Comment by redzic** [comment] 2021-11-01 17:04
Seems like the ffmpeg that you are using is broken and can't pipe y4m for some reason. Can you try downloading an ffmpeg binary from here instead (which should be configured properly): https://jeremylee.sh/bins/ffmpeg.7z

and try again? Thanks.

**Comment by phanluchoaofficial20** [comment] 2021-11-01 17:09
> Seems like the ffmpeg that you are using is broken and can't pipe y4m for some reason. Can you try downloading an ffmpeg binary from here instead (which should be configured properly): https://jeremylee.sh/bins/ffmpeg.7z
> 
> and try again? Thanks.

Your ffmpeg you can pipe now, wait me some hours i will get back, this command is encode again ?

**Comment by redzic** [comment] 2021-11-01 17:10
Sure, take your time. And yes, it's all the same commands. Just make sure that when you type `ffmpeg` in the command line it is actually using the new binary downloaded from the link I posted.

**Comment by phanluchoaofficial20** [comment] 2021-11-01 17:11
> Sure, take your time. And yes, it's all the same commands. Just make sure that when you type `ffmpeg` in the command line it is actually using the new binary downloaded from the link I posted.

Ok thanks, I want to ask one more question out of this, why i cannot encode using this Av1an ? I got error no temp found and as I see they encode very fast ?

**Comment by redzic** [comment] 2021-11-01 17:13
Not sure, I'd probably need to see the logs and output posted to figure out what the issue is with that. Let's open a separate issue for that and try to fix the scene detection here.

**Closed** 2021-11-02 03:18 UTC
