### ISSUE TITLE
Encoding stuck when --target-quality is given and --split-method not set to 'none'

### ISSUE THREAD

**Issue by ahmadrr** [master-of-zen/Av1an#365] opened 2021-09-28 07:30 UTC
I tried to encode [test.mp4](https://user-images.githubusercontent.com/46526140/122739042-3ec02900-d28b-11eb-8ef0-2e5e3e846525.mp4) with ```av1an -v " --cpu-used=6 --end-usage=q --cq-level=29 " --target-quality 94 --vmaf-path "vmaf_v0.6.1.json" -p 1 -w 4 -i d:\test.mp4 -o d:\test.mkv``` didn't work. But ```av1an -v " --cpu-used=6 --end-usage=q --cq-level=29 " --target-quality 94 --vmaf-path "vmaf_v0.6.1.json" -p 1 -w 4 --split-method none -x 95 -i d:\test.mp4 -o d:\test.mkv``` works, as well as ```av1an -v " --cpu-used=6 --end-usage=q --cq-level=29 " -p 1 -w 4 -i d:\test.mp4 -o d:\test.mkv```

Logs from the fifth (failed) attempt:
INFO [av1an_core::project] SC: Found 4 scenes
INFO [av1an_core::project] SC: Applying extra splits every 240 frames
INFO [av1an_core::project] SC: Now at 4 scenes
INFO [av1an_core::broker] Enc: 0, 105 fr
INFO [av1an_core::broker] Enc: 2, 91 fr
INFO [av1an_core::broker] Enc: 1, 89 fr
INFO [av1an_core::broker] Enc: 3, 3 fr
INFO [av1an_core::target_quality] Chunk: 00003, Rate: 4, Fr 3
INFO [av1an_core::target_quality] Probes [(94.146467, 15), (79.27741, 35)]
INFO [av1an_core::target_quality] Target Q: 15 VMAF: 94.00
INFO [av1an_core::broker] Done: 3 Fr: 3/3
INFO [av1an_core::broker] Fps: 0.57 Time: 5.2992557s
INFO [av1an_core::target_quality] Chunk: 00000, Rate: 4, Fr 105
INFO [av1an_core::target_quality] Probes [(95.699518, 35), (94.704512, 42), (94.084426, 44), (88.473074, 55)]
INFO [av1an_core::target_quality] Target Q: 44 VMAF: 94.00
INFO [av1an_core::target_quality] Chunk: 00001, Rate: 4, Fr 89
INFO [av1an_core::target_quality] Probes [(96.723708, 15), (94.812361, 27), (94.145562, 29), (90.903248, 35)]
INFO [av1an_core::target_quality] Target Q: 29 VMAF: 94.00
INFO [av1an_core::broker] Done: 0 Fr: 105/105
INFO [av1an_core::broker] Fps: 2.84 Time: 36.9406885s
INFO [av1an_core::broker] Done: 1 Fr: 89/89
INFO [av1an_core::broker] Fps: 2.09 Time: 42.5555078s

CMD:
D:\Video\av1\target\release>av1an -v " --cpu-used=6 --end-usage=q --cq-level=29 " --target-quality 94 --vmaf-path "vmaf_v0.6.1.json" -p 1 -w 4 -i "d:\test.mp4" -o "d:\test.mkv"
Scene detection
[00:00:00] [########################################################] 100% 288/288 (331.03 fps, eta 0s)
Queue: 4 Workers: 4 Passes: 1
Params: --cpu-used=6 --end-usage=q --cq-level=29
[00:05:06] [######################################>------------------]  68% 197/288 (4.50 fps, eta 20s)
Stopped

The longest time I've waited is around 20-25 minutes, before restarting. Chunk 1 (89 frames) was done in under a minute, so Chunk no 2 (91 frames) running for longer than 20 minutes and still unfinished should means that it was stuck.

**Comment by ahmadrr** [comment] 2021-10-31 05:28
> This should be fixed now.
> 
> I mean, temporarily until I get aomenc's temporal RDO bug fixed for our stupid egde case.

I use aomenc from Oct 13 2021, 13:17 UTC, built with media-autobuild-suite, it still stuck

C:\Users\Ahmad\.cargo\bin>av1an -v " --cpu-used=6 --end-usage=q --cq-level=29 " --target-quality 94 --vmaf-path "vmaf_v0.6.1.json" -p 1 -w 4 -i d:\video\test.mp4 -o d:\video\test.webm
Scene detection
[00:00:00] [########################################################################] 100% 288/288 (424.89 fps, eta 0s)
Queue: 3 Workers: 3 Passes: 1
Params: --cpu-used=6 --end-usage=q --cq-level=29
[00:06:00] [##################################################>----------------------]  69% 199/288 (5.28 fps, eta 17s)
Stopped

**Comment by dexeonify** [comment] 2021-10-31 05:57
Works fine for me. Just to be clear, Av1an is the one that needs to be updated, the issue is still not fixed in aomenc's side.

**Comment by ahmadrr** [comment] 2021-10-31 07:37
I just updated Av1an using ```cargo install --force av1an```, still the same. Building it from source has always gave me compilation errors for ffmpeg-sys-next v4.4.0 on Windows. Last time I built it without errors was on 28th Sep 2021

**Comment by redzic** [comment] 2021-10-31 07:40
@ahmadrr `cargo install` will install the latest release on crates.io, which isn't new enough to contain the fix. A new release should be coming soon but in the meantime you can try `cargo install --git https://github.com/master-of-zen/Av1an`

**Comment by redzic** [comment] 2021-11-23 19:08
Going to close this since this should be fixed in the latest version, feel free to reopen this issue if it still happens

**Closed by redzic** 2021-11-23 19:08 UTC
